#!/bin/bash
# chkconfig: 2345 90 10
# description: start or stop the ssr server
#
### BEGIN INIT INFO
# Provides: ssr
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start or stop the ssr server
### END INIT INFO

# Author: hfck

name=ssr
BIN=/root/uml-centos-64/
start(){
    bash ${BIN}run.sh start
    RETVAL=$?
    if [ "$RETVAL" = "0" ]; then
        echo "$name start success"
    else
        echo "$name start failed"
    fi
}

stop(){
	bash ${BIN}run.sh stop
}

status(){
	bash ${BIN}run.sh status
}

restart(){
	bash ${BIN}run.sh restart
}


case "$1" in
'start')
    start
    ;;
'stop')
    stop
    ;;
'status')
    status
    ;;
'restart')
    restart
    RETVAL=$?
    ;;
*)
    echo "Usage: $0 { start | stop | restart | status  }"
    RETVAL=1
    ;;
esac
exit $RETVAL
